portal/portal/urls.py
from django.contrib import admin
from django.urls import path,include
from portalapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home.as_view(),name='home'),
    path('createExam/',views.Category.as_view(),name='exam'),
    path('list/',views.Catlist.as_view(),name='list'),
    path('exam/<int:id>/',views.examlist,name='exam'),
    path('createexam/<int:id>/',views.Exam.as_view(),name='create_exam'),
    # path('qlist/<int:pk>/',views.question,name='qlist'),
    path('courses/',views.CourseEnroll.as_view(),name='enroll'),
    path('req/',views.Requests.as_view(),name='req'),
    path('det/<int:pk>/',views.Detail.as_view(),name='det'),
    path('del/<int:pk>/',views.ReqDelete.as_view(),name='del'),
    path('portalapp/',include('portalapp.urls',namespace='portalapp')),
    path('portalapp/',include('django.contrib.auth.urls')),
]

portal/portalapp/urls.py
from django.urls import path,re_path
from django.contrib.auth.views import LoginView,LogoutView
from . import views
app_name='portalapp'

urlpatterns=[
path('login/',LoginView.as_view(template_name='login.html'),name='login'),
path('logout/',LogoutView.as_view(),name='logout'),
path('signup/',views.Signup.as_view(template_name='signup.html'),name='signup'),
path('login_success/',views.LoginSuccess.as_view(),name='login_success'),
path('logout_success/',views.LogoutSuccess.as_view(),name='logout_success'),
]

portal/portalapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User,PermissionsMixin
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.
class User(User,PermissionsMixin):
    def __str__(self):
        return self.username
status_choice=(
('True','True'),
('False','False'),
)
class Courses(models.Model):
    title=models.CharField(max_length=256)
    faculty=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.title
class studentCourses(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    courses=models.ForeignKey(Courses,on_delete=models.CASCADE)
    status=models.CharField(choices=status_choice,default='False',max_length=20)
    def __str__(self):
        return self.user.username
class Exam(models.Model):
    course=models.ForeignKey(Courses,on_delete=models.CASCADE)
    title=models.CharField(default='exam',max_length=256)
    total_marks=models.PositiveIntegerField()
    start_time=models.DateTimeField(blank=True,null=True)
    end_time=models.DateTimeField(blank=True,null=True)

    def __str__(self):
        return self.title
status_choice=(
('True','True'),
('False','False'),
)
class Descriptive(models.Model):

    exam=models.ForeignKey('Exam',related_name='Descriptive',on_delete=models.CASCADE)
    question=models.CharField(max_length=300)
    maxmarks=models.PositiveIntegerField()
    marks=models.PositiveIntegerField()
    answer=models.CharField(max_length=1000,blank=True)
    upload=models.FileField(upload_to='uploads/')

    def __str__(self):
        return 'Que'

class IntegerType(models.Model):

    exam=models.ForeignKey('Exam',related_name='Integer',on_delete=models.CASCADE)
    question=models.CharField(max_length=300)
    maxmarks=models.PositiveIntegerField()
    marks=models.PositiveIntegerField()
    answer=models.PositiveIntegerField(default=0,validators=[MaxValueValidator(9),MinValueValidator(0)])
    def __str__(self):
        return 'Que'
class MCQ(models.Model):

    exam=models.ForeignKey('Exam',related_name='MCQ',on_delete=models.CASCADE)
    question=models.CharField(max_length=300)
    maxmarks=models.PositiveIntegerField()
    marks=models.PositiveIntegerField()
    def __str__(self):
        return 'Que'

class Choice(models.Model):

    question=models.ForeignKey('MCQ',related_name='choices',on_delete=models.CASCADE)
    iscorrect=models.BooleanField()
    text=models.CharField(max_length=50)
    position=models.PositiveIntegerField()

    def __str__(self):
        return 'Que'

    class META:
        unique_together=[
        ("question","text"),
        ("question","position")
        ]
        ordering = ("position",)

class MultiCorrectMCQ(models.Model):

    exam=models.ForeignKey('Exam',related_name='MultiCorrectMCQ',on_delete=models.CASCADE)
    question=models.CharField(max_length=300)
    maxmarks=models.PositiveIntegerField()
    marks=models.PositiveIntegerField()
    correct=models.PositiveIntegerField()
    incorrect=models.PositiveIntegerField()
    ispartial=models.BooleanField()
    def __str__(self):
        return 'Que'

class MChoice(models.Model):

    question=models.ForeignKey('MultiCorrectMCQ',related_name='choices',on_delete=models.CASCADE)
    iscorrect=models.BooleanField()
    text=models.CharField(max_length=50)
    position=models.PositiveIntegerField()
    def __str__(self):
        return 'Que'

    class META:
        unique_together=[
        ("question","text"),
        ("question","position")
        ]
        ordering = ("position",)

class TrueFalse(models.Model):

    exam=models.ForeignKey('Exam',related_name='TrueFalse',on_delete=models.CASCADE)
    question=models.CharField(max_length=300)
    maxmarks=models.PositiveIntegerField()
    marks=models.PositiveIntegerField()
    iscorrect=models.BooleanField()
    def __str__(self):
        return 'Que'

class FillBlanks(models.Model):

    exam=models.ForeignKey('Exam',related_name='FillBlanks',on_delete=models.CASCADE)
    question=models.CharField(max_length=300)
    answer=models.CharField(max_length=30)
    maxmarks=models.PositiveIntegerField()
    marks=models.PositiveIntegerField()
    def __str__(self):
        return 'Que'

portal/portalapp/forms.py
from django import forms
from portalapp.models import (Exam,Descriptive,MCQ,MultiCorrectMCQ,
IntegerType,Choice,MChoice,TrueFalse,FillBlanks,Courses,studentCourses)
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import MaxLengthValidator,MinLengthValidator
class UserCreateForm(UserCreationForm):
    class Meta:
        fields =('first_name','last_name','username','email','password1','password2')
        model = get_user_model()

portal/portalapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,View,ListView,DetailView,CreateView,DeleteView,UpdateView
from django.urls import reverse_lazy,reverse
from django.contrib.auth.models import User
from portalapp.models import (Exam,Descriptive,MCQ,MultiCorrectMCQ,
IntegerType,Choice,MChoice,TrueFalse,FillBlanks,Courses,studentCourses)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
from . import forms
from django.forms import DateInput
# Create your views here.
from django.contrib.auth import get_user_model
class Home(TemplateView):
    template_name='base.html'

class Category(LoginRequiredMixin,CreateView):
    template_name='portalapp/cat.html'
    model=Courses
    fields=('title',)
    login_url=reverse_lazy('portalapp:login')
    success_url=reverse_lazy('portalapp:login_success')
    def form_valid(self,form):
        form.instance.faculty=self.request.user
        return super(Category,self).form_valid(form)
class Signup(CreateView):
    form_class = forms.UserCreateForm
    template_name='signup.html'
    success_url=reverse_lazy('portalapp:login')
class Examlist(LoginRequiredMixin,ListView):
    template_name='portalapp/exam_list.html'
    context_object_name='exam_list'
    model=Exam
    def get_queryset(self):
        qs=super(Examlist,self).get_queryset()
        return qs.filter(course__exact=self.kwargs['id'])

@login_required
def examlist(request,id):
    qs=Exam.objects.filter(course_id=id)
    return render(request,'portalapp/exam_list.html',{'exam_list':qs,'pk':id})
class Exam(LoginRequiredMixin,CreateView):
    template_name='portalapp/create_exam.html'
    fields=('title','total_marks','start_time','end_time')

    login_url=reverse_lazy('portalapp:login')
    success_url=reverse_lazy('portalapp:login_success')
    model=Exam
    def form_valid(self,form):
        form.instance.course_id=self.kwargs['pk']
        return super(Exam,self).form_valid(form)
class Catlist(LoginRequiredMixin,ListView):
    context_object_name='catlist'
    template_name='portalapp/cat_list.html'
    model=Courses
    login_url=reverse_lazy('portalapp:login')
    success_url=reverse_lazy('portalapp:login_success')
    def get_queryset(self):
        qs=super(Catlist,self).get_queryset()
        return qs.filter(faculty__exact=self.request.user)

# @login_required
# def question(request,pk):
#     try:
#         tf=models.TF.objects.filter(exam_id=pk)
#     except:pass
#     try:
#         dis=models.discriptive.objects.filter(exam_id=pk)
#     except:pass
#     try:
#         fill=models.fillnblanks.objects.filter(exam_id=pk)
#     except:pass
#     return render(request,'eapp/q_list.html',{'tf':tf,'pk':pk,'dis':dis,'fill':fill})
#
# class TFV(LoginRequiredMixin,CreateView):
#     model=models.TF
#     template_name='eapp/tf.html'
#     login_url=reverse_lazy('portalapp:login')
#     success_url=reverse_lazy('portalapp:login_success')
#     fields=('question','ans','marks')
#     def form_valid(self,form):
#         form.instance.exam_id=self.kwargs['pk']
#         return super(TFV,self).form_valid(form)
# class DisV(LoginRequiredMixin,CreateView):
#     model=models.discriptive
#     template_name='eapp/tf.html'
#     success_url=reverse_lazy('home')
#     login_url=reverse_lazy('login')
#     fields=('question','marks')
#     def form_valid(self,form):
#         form.instance.exam_id=self.kwargs['pk']
#         return super(DisV,self).form_valid(form)
# class fillV(LoginRequiredMixin,CreateView):
#     model=models.fillnblanks
#     template_name='eapp/tf.html'
#     success_url=reverse_lazy('home')
#     login_url=reverse_lazy('login')
#     fields=('question','marks')
#     def form_valid(self,form):
#         form.instance.exam_id=self.kwargs['pk']
#         return super(fillV,self).form_valid(form)
class CourseEnroll(LoginRequiredMixin,CreateView):
    model=studentCourses
    template_name='portalapp/cour.html'
    login_url=reverse_lazy('portalapp:login')
    success_url=reverse_lazy('portalapp:login_success')
    fields=('courses',)
    def form_valid(self,form):
        form.instance.user=self.request.user
        return super(CourseEnroll,self).form_valid(form)
class AdminStaffRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):

    login_url=reverse_lazy('login')
    success_url=reverse_lazy('home')
    def test_func(self):
        return self.request.user.is_superuser
class Requests(AdminStaffRequiredMixin,ListView):
    model=studentCourses
    template_name='portalapp/request.html'
    context_object_name='list'
    def get_queryset(self):
        qs=super(Requests,self).get_queryset()
        return qs.filter(status__exact='False')
class Detail(AdminStaffRequiredMixin,UpdateView):
    model=studentCourses
    template_name='portalapp/details.html'
    fields=('status',)
    success_url=reverse_lazy('home')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        req=studentCourses.objects.get(id=self.kwargs['pk'])

        context["usname"] = req
        context["pk"]=self.kwargs['pk']
        return context
class ReqDelete(AdminStaffRequiredMixin,DeleteView):
    model=studentCourses
    success_url='/'
class LoginSuccess(TemplateView):
    template_name='login_success.html'
class LogoutSuccess(TemplateView):
    template_name='logout_success.html'

portal/portalapp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Examination portal</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'index.css' %}" >
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous"> -->
    <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js" integrity="sha384-3Nqiqht3ZZEO8FKj7GR1upiI385J92VwWNLj+FqHxtLYxd9l+WYpeqSOrLh0T12c" crossorigin="anonymous"></script>

        <!-- scripts -->

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <!-- <script src="app.js"></script> -->
</head>
<body>

    <header>
        <h1>Examination portal</h1>
    </header>
    <section id="nav-bar">
        <nav class="navbar navbar-expand-lg ">
            <div class="container-fluid">
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon">Drop</span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav navbar-collapse">
                  <li class="nav-item" >
                    <a class="nav-link"  href="{% url 'home' %}">Home</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'list' %}">Courses List</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'enroll' %}">Courses Enroll</a>
                  </li>
                  {% if user.is_authenticated %}
                  <li class="nav-item">
              <a class="nav-link" href="{% url 'exam' %}">Create Courses</a>
            </li><li class="nav-item">
              <a class="nav-link" href="{% url 'req' %}">Enroll Requests</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown link
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'portalapp:logout' %}">Logout</a>
                  </li>

                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'portalapp:login' %}">Login</a>
                  </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </nav>
    </section>

    <div class="container">
      {% block body_block%}

      {% endblock %}
    </div>

    <footer class="new_footer_area bg_color">
        <div class="new_footer_top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6">
                        <div class="f_widget about-widget pl_70 wow fadeInLeft" data-wow-delay="0.4s" style="visibility: visible; animation-delay: 0.4s; animation-name: fadeInLeft;">
                            <h3 class="f-title f_600 t_color f_size_18">Download</h3>
                            <ul class="list-unstyled f_list">
                                <li><a href="#">Company</a></li>
                                <li><a href="#">Desktop</a></li>
                                <li><a href="#">Other Projects</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="f_widget about-widget pl_70 wow fadeInLeft" data-wow-delay="0.6s" style="visibility: visible; animation-delay: 0.6s; animation-name: fadeInLeft;">
                            <h3 class="f-title f_600 t_color f_size_18">Help</h3>
                            <ul class="list-unstyled f_list">
                                <li><a href="#">FAQ</a></li>
                                <li><a href="#">Term &amp; conditions</a></li>
                                <li><a href="#">Reporting</a></li>
                                <li><a href="#">Documentation</a></li>
                                <li><a href="#">Support Policy</a></li>
                                <li><a href="#">Privacy</a></li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
            <div class="footer_bg">
                <div class="footer_bg_one"></div>
                <div class="footer_bg_two"></div>
            </div>
        </div>
        <div class="footer_bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-sm-7">
                        <p class="mb-0 f_400">© Exam Portal 2021 All rights reserved.</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

portal/portalapp/templates/index.html
{% extends 'base.html' %}
{% block body_block %}
<h1>Hello !!</h1>
{% endblock %}

portal/portalapp/templates/login.html
{% extends 'base.html' %}
{% block body_block %}
<div class="jumbotron ">
  <div class="login-container">
    <form class="login-form" method="POST">

      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" id="login-submit" value="Login">

      <a href="{%url 'portalapp:signup'%}" id="signup-submit">Dont have an account? Sign Up</a>
    </form>
  </div>
  </div>

{% endblock %}

portal/portalapp/templates/login_success.html
{% extends 'base.html' %}
{% block body_block %}
<h1>You are Logged in Successfully!!</h1>
{% endblock %}

portal/portalapp/templates/logout_success.html
{% extends 'base.html' %}
{% block body_block %}
<h1>Thank you for Visiting. You are Logged out Successfully!!</h1>
{% endblock %}

portal/portalapp/templates/signup.html
{% extends 'base.html' %}
{% block body_block %}
<div class="jumbotron">
<form class="login-form" method="POST">
{% csrf_token %}
{{ form.as_p}}
<input type="submit" id="login-submit" value="Sign UP">
</form>
</div>
{% endblock %}